### ISSUE TITLE
Program error with output

### ISSUE THREAD

**Issue by dhrititandon** [XiaoTaoWang/TADLib#12]
Upon running hitad, I get the following text. My input command is [ hitad --output test_50000.txt -d meta_file_50kb --logFile hitad.log ]. Although the prompt gives a 'done' message, there is no output file and I don't think that the program even proceeds with the TAD parsing.

root                      INFO    @ 10/17/19 18:16:14:
# ARGUMENT LIST:
# Output file name = test_50000.txt
# Hi-C datasets = {500000: {'rep1': '/scratch/network/dtandon/HiCLiver2/SRR17.output_50000.cool'}}
# Column for matrix balancing = weight
# Excluded chromosomes = ['chrY', 'chrM']
# Maximum domain size = 4000000
# Column for DI track = DIs
# Number of processes used = 1
# Remove cache data = False
# Log file name = hitad.log
root                      INFO    @ 10/17/19 18:16:16: Parsing Hi-C datasets ...
root                      INFO    @ 10/17/19 21:01:05: Done!

**Comment by dhrititandon** [comment]
I forgot to mention that in my log file I get the following error

Traceback (most recent call last):
  File "/home/dtandon/.conda/envs/hitad/bin/hitad", line 121, in run
    G.learning(cpu_core=args.cpu_core)
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/tadlib/hitad/genomeLev.py", line 199, in learning
    seqs = self.train_data(res, rep)
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/tadlib/hitad/genomeLev.py", line 176, in train_data
    tmpcache.calDI(tmpcache.windows, 0)
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/tadlib/hitad/chromLev.py", line 356, in calDI
    lthre = np.percentile(self.DIs[self.DIs<0], 0.1)
  File "<__array_function__ internals>", line 6, in percentile
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3713, in percentile
    a, q, axis, out, overwrite_input, interpolation, keepdims)
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3833, in _quantile_unchecked
    interpolation=interpolation)
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3410, in _ureduce
    r = func(a, **kwargs)
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3948, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "<__array_function__ internals>", line 6, in take
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 194, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/dtandon/.conda/envs/hitad/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.

**Comment by AyushSemwal** [comment]
I am also having the same issue. Were you able to figure out?

**Comment by rachadele** [comment]
Nope. I ended up using Juicer tools to generate a matrix and call TADs.
Works much better!
