### ISSUE TITLE
KeyError: 0

### ISSUE THREAD

**Issue by wbszhu** [XiaoTaoWang/TADLib#21]
Hello,
I am trying to identify TAD using domaincaller Or hitad. But both of them return the same error back. I am so confused.
```
cool=PI.balance.mcool::/resolutions/40000
#hitad -O ${i}_tad.txt -d config-${i}.txt --logFile hitad-${i}.log 
domaincaller --uri $cool  -O test.tad.bed --exclude chrMT chrX chrY  --DI-output test.DIs.bedGraph --removeCache
```
```
Traceback (most recent call last):
  File "/public/home/luzhang/miniconda3/envs/hic/bin/domaincaller", line 97, in run
    G.learning(cpu_core=args.cpu_core)
  File "/public/home/luzhang/miniconda3/envs/hic/lib/python3.7/site-packages/tadlib/domaincaller/genomeLev.py", line 87, in learning
    model = self.oriHMMParams()
  File "/public/home/luzhang/miniconda3/envs/hic/lib/python3.7/site-packages/tadlib/hitad/genomeLev.py", line 172, in oriHMMParams
    hmm.bake()
  File "pomegranate/hmm.pyx", line 755, in pomegranate.hmm.HiddenMarkovModel.bake
  File "/public/home/luzhang/miniconda3/envs/hic/lib/python3.7/site-packages/networkx/classes/reportviews.py", line 193, in __getitem__
    return self._nodes[n]
KeyError: 0
```
Hope you can help me, Thanks in advance.
Lu Zhang

**Comment by wbszhu** [comment]
PS:

domaincaller -v
domaincaller 0.4.5-r1

hitad -v
hitad 0.4.5-r1

**Comment by wbszhu** [comment]
Hi,

I have solved this. it is because the networkx version is not 1.X.
And pay attention to the joblib version need to be 0.17.0.

Thanks.

**Comment by XiaoTaoWang** [comment]
Great, thanks!
