### ISSUE TITLE
Error running hitad

### ISSUE THREAD

**Issue by aminakur** [XiaoTaoWang/TADLib#23]
I was running hitad with the following parameters:
`hitad --output az_hitad.txt -d meta_file --logFile hitad.log --maxsize 3000000 -p 8`

meta_file
```
res:200
	rep1:/scratch/ak/az_/az.cool

```
After 2 hr, run got terminated. hitad.log file:
```
root                      DEBUG   @ 12/13/22 10:21:50: Learning HMM parameters for each dataset ...
tadlib.hitad.genomeLev    DEBUG   @ 12/13/22 10:21:50:   resolution: 200, rep1
Traceback (most recent call last):
  File "/ext3/py3.7.1/lib/python3.7/site-packages/joblib/parallel.py", line 862, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/ext3/py3.7.1/lib/python3.7/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ext3/py3.7.1/bin/hitad", line 126, in run
    G.learning(cpu_core=args.cpu_core)
  File "/ext3/py3.7.1/lib/python3.7/site-packages/tadlib/hitad/genomeLev.py", line 212, in learning
    stop_threshold=1e-5, n_jobs=cpu_core, verbose=False)
  File "pomegranate/hmm.pyx", line 2576, in pomegranate.hmm.HiddenMarkovModel.fit
  File "pomegranate/hmm.pyx", line 2619, in genexpr
  File "/ext3/py3.7.1/lib/python3.7/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/ext3/py3.7.1/lib/python3.7/site-packages/joblib/parallel.py", line 873, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "pomegranate/hmm.pyx", line 2619, in genexpr
TypeError: delayed() got an unexpected keyword argument 'check_pickle'
```

**Comment by hanshanmengqi** [comment]
Hi @MyBiscuit,
Do you resolve the problem?

Han

**Comment by hanshanmengqi** [comment]
Just for future users. 
Please confirm joblib==0.13.2, after that, hitad should be work!

Best,
Han
