### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by bam-xiaomu** [XiaoTaoWang/TADLib#27]
Hello,this is my code:
hitad -O 3H-1-T1_25kb_hitad.domain -d hitad.txt -W RAW
But it has a error:
Traceback (most recent call last):
  File "/store/zlzhang/miniconda3/envs/hitad_env/bin/hitad", line 141, in <module>
    run()
  File "/store/zlzhang/miniconda3/envs/hitad_env/bin/hitad", line 76, in run
    args, commands = getargs()
  File "/store/zlzhang/miniconda3/envs/hitad_env/bin/hitad", line 70, in getargs
    args = parser.parse_args(commands)
  File "/store/zlzhang/miniconda3/envs/hitad_env/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/store/zlzhang/miniconda3/envs/hitad_env/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/store/zlzhang/miniconda3/envs/hitad_env/lib/python3.7/argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/store/zlzhang/miniconda3/envs/hitad_env/lib/python3.7/argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "/store/zlzhang/miniconda3/envs/hitad_env/lib/python3.7/argparse.py", line 1845, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/store/zlzhang/miniconda3/envs/hitad_env/lib/python3.7/argparse.py", line 2376, in _get_values
    value = self._get_value(action, arg_string)
  File "/store/zlzhang/miniconda3/envs/hitad_env/lib/python3.7/argparse.py", line 2409, in _get_value
    result = type_func(arg_string)
  File "/store/zlzhang/miniconda3/envs/hitad_env/bin/hitad", line 20, in datasets_convert
    res = int(parse[1])
IndexError: list index out of range

I don't know why,can you help me?

**Comment by bam-xiaomu** [comment]
I'm sorry,I get it.
