### ISSUE TITLE
hitad : error

### ISSUE THREAD

**Issue by yyzheng-216** [XiaoTaoWang/TADLib#28]
Hello!
I am trying to plot the output of HiTAD after running it on a single resolution .cool file, but when I ran some chromosomes, it succeeded, but some chromosomes failed. And the program does not end after encountering an error.

This is my code:
 $ cat 1.hitad.log
root                      INFO    @ 09/12/24 17:47:01:
# ARGUMENT LIST:
# Output file name = ./10K/Bol_10000.matrix.chr1.cool.hitad.txt
# Hi-C datasets = {10000: {'rep1': '/Bol/TAD/10K/Bol_10000.matrix.chr1.cool::10000'}}
# Column for matrix balancing = weight
# Excluded chromosomes = ['chrY', 'chrM']
# Minimum Chromosome Size = 1000000
# Maximum domain size = 4000000
# Column for DI track = DIs
# Number of processes used = 1
# Remove cache data = False
# Log file name = log/Bol_10000.matrix.chr1.cool.hitad.log
numexpr.utils             INFO    @ 09/12/24 17:47:02: Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
numexpr.utils             INFO    @ 09/12/24 17:47:02: NumExpr defaulting to 8 threads.
root                      INFO    @ 09/12/24 17:47:06: Parsing Hi-C datasets ...
root                      INFO    @ 09/12/24 17:47:09: Done!
root                      INFO    @ 09/12/24 17:47:13: Identifying hierarchical domains ...
Process SubProcess-1:
Traceback (most recent call last):
  File "/home/yyzheng/software/mambaforge/miniforge/envs/TADLib/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/yyzheng/software/mambaforge/miniforge/envs/TADLib/lib/python3.7/site-packages/tadlib/hitad/genomeLev.py", line 256, in run
    worker(chrom, res, rep)
  File "/home/yyzheng/software/mambaforge/miniforge/envs/TADLib/lib/python3.7/site-packages/tadlib/hitad/genomeLev.py", line 263, in worker
    curChrom.callDomain()
  File "/home/yyzheng/software/mambaforge/miniforge/envs/TADLib/lib/python3.7/site-packages/tadlib/hitad/chromLev.py", line 761, in callDomain
    self.oriIter({})
  File "/home/yyzheng/software/mambaforge/miniforge/envs/TADLib/lib/python3.7/site-packages/tadlib/hitad/chromLev.py", line 689, in oriIter
    tmpDomains = self.minCore(self.regionDIs)
  File "/home/yyzheng/software/mambaforge/miniforge/envs/TADLib/lib/python3.7/site-packages/tadlib/hitad/chromLev.py", line 557, in minCore
    domains = self.pipe(seq, region[0])
  File "/home/yyzheng/software/mambaforge/miniforge/envs/TADLib/lib/python3.7/site-packages/tadlib/hitad/chromLev.py", line 527, in pipe
    bounds = self._getBounds(self.viterbi(seq), junctions=['30'])
  File "/home/yyzheng/software/mambaforge/miniforge/envs/TADLib/lib/python3.7/site-packages/tadlib/hitad/chromLev.py", line 457, in viterbi
    path = [int(s.name) for i, s in self.hmm.viterbi(seq)[1][1:-1]]
TypeError: 'NoneType' object is not subscriptable

**Comment by Accompany0313** [comment]
Have you solved this problem? I had the same problem
